### ISSUE TITLE
How to configure the image max file size?

### ISSUE THREAD

**Issue by martnst** [quru/qis#32]
Hi, when uploading larger images we get an error looking like this. 

![image](https://user-images.githubusercontent.com/3084607/75029204-e9f77d00-54a1-11ea-9f50-cea627505ee2.png)

- Firstly it is a terrible UX as the actually error message is missing, so it is not clear what went wrong.
- Secondly, how can I configure the max file size for uploading images?

**Comment by qururoland** [comment]
Hi Martin,
Not sure what has happened here. Normally the errors are described in understandable English so it strikes me that this is a new error. Can you tell us how big the file is and what type it is and I will see if I can reproduce it.

**Comment by fozcode** [comment]
The default max upload size is 1GB and defined here:
https://github.com/quru/qis/blob/758c4486566e2fa331fb0eb0bb227d9ef194bf7a/src/imageserver/conf/base_settings.py#L152

It can be changed by setting a new value in `/opt/qis/conf/local_settings.py`

I would guess the error message is missing because the error is raised from Flask rather than from user code but yes it should be shown either way.

**Comment by martnst** [comment]
I see. For us it seems to be related to image sizes as it works with very small images around 1MB.

**Comment by martnst** [comment]
We have QIS running via docker-compose on a [DigitalOcean Droplet](https://marketplace.digitalocean.com/apps/docker). 

```
$cat docker-compose.yml

#
# Sample QIS docker-compose launch file
#
# Launches containers running:
# QIS Application Server, Postgres and Memcached
#
# Required environment variables:
#
#   QIS_HOSTNAME - host name that the QIS web server should serve from
#   QIS_DATA_DIR - host path in which to store QIS images, database, and log files
#
# The data directory ends up containing $QIS_DATA_DIR/images
#                                       $QIS_DATA_DIR/data
#                                       $QIS_DATA_DIR/logs
#
# The environment variables can be persisted in a text file called .env.
# See https://docs.docker.com/compose/env-file/
#

version: "2"

services:
  qis_db:
    image: quru/qis-postgres
    volumes:
      - "$QIS_DATA_DIR/data:/opt/qis/data"
    mem_limit: 512M
    environment:
      - PG_USER=qis
      - PG_PASSWORD=qisdbpass
      - PG_SHARED_BUFFERS=256MB
      - PG_EFFECTIVE_CACHE_SIZE=512MB

  qis_cache:
    image: quru/qis-memcached
    mem_limit: 512M
    environment:
      - MEMCACHED_SIZE=512

  qis_as:
    image: quru/qis-as
    ports:
      - "8080:80"
      - "4443:443"
    volumes:
      - "$QIS_DATA_DIR/images:/opt/qis/images"
      - "$QIS_DATA_DIR/logs/qis:/opt/qis/logs"
      - "$QIS_DATA_DIR/logs/apache:/var/log/apache2"
    environment:
      - HOSTNAME=$QIS_HOSTNAME
      - DB_USER=qis
      - DB_PASSWORD=qisdbpass
      - HTTP_PROCESSES=2
      - HTTPS_PROCESSES=2
    depends_on:
      - qis_cache
      - qis_db
```

I noticed the memcahed is not running anymore. Could the be the cause? 

```$ docker ps
CONTAINER ID        IMAGE               COMMAND              CREATED             STATUS                  PORTS                                         NAMES
79a1e4a7295d        quru/qis-as         "/run-qis.sh"        4 months ago        Up 4 months (healthy)   0.0.0.0:8080->80/tcp, 0.0.0.0:4443->443/tcp   qis_qis_as_1
e5d2dec1e49e        quru/qis-postgres   "/run-postgres.sh"   4 months ago        Up 4 months (healthy)   5432/tcp                                      qis_qis_db_1
```
